[project]
name = "cognee-starter"
version = "0.1.0"
description = "Starter project which can be harvested for parts"
readme = "README.md"

requires-python = ">=3.10"

dependencies = [
    "cognee>=0.1.24",
]
